import { CurrencyConfig } from "../core/currency";
import { AED_CONFIG } from "../currencies/iso4217/aed";
import { AFN_CONFIG } from "../currencies/iso4217/afn";
import { ALL_CONFIG } from "../currencies/iso4217/all";
import { AMD_CONFIG } from "../currencies/iso4217/amd";
import { ANG_CONFIG } from "../currencies/iso4217/ang";
import { AOA_CONFIG } from "../currencies/iso4217/aoa";
import { ARS_CONFIG } from "../currencies/iso4217/ars";
import { AUD_CONFIG } from "../currencies/iso4217/aud";
import { AWG_CONFIG } from "../currencies/iso4217/awg";
import { AZN_CONFIG } from "../currencies/iso4217/azn";
import { BAM_CONFIG } from "../currencies/iso4217/bam";
import { BBD_CONFIG } from "../currencies/iso4217/bbd";
import { BDT_CONFIG } from "../currencies/iso4217/bdt";
import { BGN_CONFIG } from "../currencies/iso4217/bgn";
import { BHD_CONFIG } from "../currencies/iso4217/bhd";
import { BIF_CONFIG } from "../currencies/iso4217/bif";
import { BMD_CONFIG } from "../currencies/iso4217/bmd";
import { BND_CONFIG } from "../currencies/iso4217/bnd";
import { BOB_CONFIG } from "../currencies/iso4217/bob";
import { BOV_CONFIG } from "../currencies/iso4217/bov";
import { BRL_CONFIG } from "../currencies/iso4217/brl";
import { BSD_CONFIG } from "../currencies/iso4217/bsd";
import { BTN_CONFIG } from "../currencies/iso4217/btn";
import { BWP_CONFIG } from "../currencies/iso4217/bwp";
import { BYN_CONFIG } from "../currencies/iso4217/byn";
import { BZD_CONFIG } from "../currencies/iso4217/bzd";
import { CAD_CONFIG } from "../currencies/iso4217/cad";
import { CDF_CONFIG } from "../currencies/iso4217/cdf";
import { CHE_CONFIG } from "../currencies/iso4217/che";
import { CHF_CONFIG } from "../currencies/iso4217/chf";
import { CHW_CONFIG } from "../currencies/iso4217/chw";
import { CLF_CONFIG } from "../currencies/iso4217/clf";
import { CLP_CONFIG } from "../currencies/iso4217/clp";
import { CNY_CONFIG } from "../currencies/iso4217/cny";
import { COP_CONFIG } from "../currencies/iso4217/cop";
import { COU_CONFIG } from "../currencies/iso4217/cou";
import { CRC_CONFIG } from "../currencies/iso4217/crc";
import { CUC_CONFIG } from "../currencies/iso4217/cuc";
import { CUP_CONFIG } from "../currencies/iso4217/cup";
import { CVE_CONFIG } from "../currencies/iso4217/cve";
import { CZK_CONFIG } from "../currencies/iso4217/czk";
import { DJF_CONFIG } from "../currencies/iso4217/djf";
import { DKK_CONFIG } from "../currencies/iso4217/dkk";
import { DOP_CONFIG } from "../currencies/iso4217/dop";
import { DZD_CONFIG } from "../currencies/iso4217/dzd";
import { EGP_CONFIG } from "../currencies/iso4217/egp";
import { ERN_CONFIG } from "../currencies/iso4217/ern";
import { ETB_CONFIG } from "../currencies/iso4217/etb";
import { EUR_CONFIG } from "../currencies/iso4217/eur";
import { FJD_CONFIG } from "../currencies/iso4217/fjd";
import { FKP_CONFIG } from "../currencies/iso4217/fkp";
import { GBP_CONFIG } from "../currencies/iso4217/gbp";
import { GEL_CONFIG } from "../currencies/iso4217/gel";
import { GHS_CONFIG } from "../currencies/iso4217/ghs";
import { GIP_CONFIG } from "../currencies/iso4217/gip";
import { GMD_CONFIG } from "../currencies/iso4217/gmd";
import { GNF_CONFIG } from "../currencies/iso4217/gnf";
import { GTQ_CONFIG } from "../currencies/iso4217/gtq";
import { GYD_CONFIG } from "../currencies/iso4217/gyd";
import { HKD_CONFIG } from "../currencies/iso4217/hkd";
import { HNL_CONFIG } from "../currencies/iso4217/hnl";
import { HRK_CONFIG } from "../currencies/iso4217/hrk";
import { HTG_CONFIG } from "../currencies/iso4217/htg";
import { HUF_CONFIG } from "../currencies/iso4217/huf";
import { IDR_CONFIG } from "../currencies/iso4217/idr";
import { ILS_CONFIG } from "../currencies/iso4217/ils";
import { INR_CONFIG } from "../currencies/iso4217/inr";
import { IQD_CONFIG } from "../currencies/iso4217/iqd";
import { IRR_CONFIG } from "../currencies/iso4217/irr";
import { ISK_CONFIG } from "../currencies/iso4217/isk";
import { JMD_CONFIG } from "../currencies/iso4217/jmd";
import { JOD_CONFIG } from "../currencies/iso4217/jod";
import { JPY_CONFIG } from "../currencies/iso4217/jpy";
import { KES_CONFIG } from "../currencies/iso4217/kes";
import { KGS_CONFIG } from "../currencies/iso4217/kgs";
import { KHR_CONFIG } from "../currencies/iso4217/khr";
import { KMF_CONFIG } from "../currencies/iso4217/kmf";
import { KPW_CONFIG } from "../currencies/iso4217/kpw";
import { KRW_CONFIG } from "../currencies/iso4217/krw";
import { KWD_CONFIG } from "../currencies/iso4217/kwd";
import { KYD_CONFIG } from "../currencies/iso4217/kyd";
import { KZT_CONFIG } from "../currencies/iso4217/kzt";
import { LAK_CONFIG } from "../currencies/iso4217/lak";
import { LBP_CONFIG } from "../currencies/iso4217/lbp";
import { LKR_CONFIG } from "../currencies/iso4217/lkr";
import { LRD_CONFIG } from "../currencies/iso4217/lrd";
import { LSL_CONFIG } from "../currencies/iso4217/lsl";
import { LYD_CONFIG } from "../currencies/iso4217/lyd";
import { MAD_CONFIG } from "../currencies/iso4217/mad";
import { MDL_CONFIG } from "../currencies/iso4217/mdl";
import { MGA_CONFIG } from "../currencies/iso4217/mga";
import { MKD_CONFIG } from "../currencies/iso4217/mkd";
import { MMK_CONFIG } from "../currencies/iso4217/mmk";
import { MNT_CONFIG } from "../currencies/iso4217/mnt";
import { MOP_CONFIG } from "../currencies/iso4217/mop";
import { MRU_CONFIG } from "../currencies/iso4217/mru";
import { MUR_CONFIG } from "../currencies/iso4217/mur";
import { MVR_CONFIG } from "../currencies/iso4217/mvr";
import { MWK_CONFIG } from "../currencies/iso4217/mwk";
import { MXN_CONFIG } from "../currencies/iso4217/mxn";
import { MXV_CONFIG } from "../currencies/iso4217/mxv";
import { MYR_CONFIG } from "../currencies/iso4217/myr";
import { MZN_CONFIG } from "../currencies/iso4217/mzn";
import { NAD_CONFIG } from "../currencies/iso4217/nad";
import { NGN_CONFIG } from "../currencies/iso4217/ngn";
import { NIO_CONFIG } from "../currencies/iso4217/nio";
import { NOK_CONFIG } from "../currencies/iso4217/nok";
import { NPR_CONFIG } from "../currencies/iso4217/npr";
import { NZD_CONFIG } from "../currencies/iso4217/nzd";
import { OMR_CONFIG } from "../currencies/iso4217/omr";
import { PAB_CONFIG } from "../currencies/iso4217/pab";
import { PEN_CONFIG } from "../currencies/iso4217/pen";
import { PGK_CONFIG } from "../currencies/iso4217/pgk";
import { PHP_CONFIG } from "../currencies/iso4217/php";
import { PKR_CONFIG } from "../currencies/iso4217/pkr";
import { PLN_CONFIG } from "../currencies/iso4217/pln";
import { PYG_CONFIG } from "../currencies/iso4217/pyg";
import { QAR_CONFIG } from "../currencies/iso4217/qar";
import { RON_CONFIG } from "../currencies/iso4217/ron";
import { RSD_CONFIG } from "../currencies/iso4217/rsd";
import { RUB_CONFIG } from "../currencies/iso4217/rub";
import { RWF_CONFIG } from "../currencies/iso4217/rwf";
import { SAR_CONFIG } from "../currencies/iso4217/sar";
import { SBD_CONFIG } from "../currencies/iso4217/sbd";
import { SCR_CONFIG } from "../currencies/iso4217/scr";
import { SDG_CONFIG } from "../currencies/iso4217/sdg";
import { SEK_CONFIG } from "../currencies/iso4217/sek";
import { SGD_CONFIG } from "../currencies/iso4217/sgd";
import { SHP_CONFIG } from "../currencies/iso4217/shp";
import { SLL_CONFIG } from "../currencies/iso4217/sll";
import { SOS_CONFIG } from "../currencies/iso4217/sos";
import { SRD_CONFIG } from "../currencies/iso4217/srd";
import { SSP_CONFIG } from "../currencies/iso4217/ssp";
import { STN_CONFIG } from "../currencies/iso4217/stn";
import { SVC_CONFIG } from "../currencies/iso4217/svc";
import { SYP_CONFIG } from "../currencies/iso4217/syp";
import { SZL_CONFIG } from "../currencies/iso4217/szl";
import { THB_CONFIG } from "../currencies/iso4217/thb";
import { TJS_CONFIG } from "../currencies/iso4217/tjs";
import { TMT_CONFIG } from "../currencies/iso4217/tmt";
import { TND_CONFIG } from "../currencies/iso4217/tnd";
import { TOP_CONFIG } from "../currencies/iso4217/top";
import { TRY_CONFIG } from "../currencies/iso4217/try";
import { TTD_CONFIG } from "../currencies/iso4217/ttd";
import { TWD_CONFIG } from "../currencies/iso4217/twd";
import { TZS_CONFIG } from "../currencies/iso4217/tzs";
import { UAH_CONFIG } from "../currencies/iso4217/uah";
import { UGX_CONFIG } from "../currencies/iso4217/ugx";
import { USD_CONFIG } from "../currencies/iso4217/usd";
import { USN_CONFIG } from "../currencies/iso4217/usn";
import { UYI_CONFIG } from "../currencies/iso4217/uyi";
import { UYU_CONFIG } from "../currencies/iso4217/uyu";
import { UYW_CONFIG } from "../currencies/iso4217/uyw";
import { UZS_CONFIG } from "../currencies/iso4217/uzs";
import { VES_CONFIG } from "../currencies/iso4217/ves";
import { VND_CONFIG } from "../currencies/iso4217/vnd";
import { VUV_CONFIG } from "../currencies/iso4217/vuv";
import { WST_CONFIG } from "../currencies/iso4217/wst";
import { XAF_CONFIG } from "../currencies/iso4217/xaf";
import { XCD_CONFIG } from "../currencies/iso4217/xcd";
import { XOF_CONFIG } from "../currencies/iso4217/xof";
import { XPF_CONFIG } from "../currencies/iso4217/xpf";
import { YER_CONFIG } from "../currencies/iso4217/yer";
import { ZAR_CONFIG } from "../currencies/iso4217/zar";
import { ZMW_CONFIG } from "../currencies/iso4217/zmw";
import { ZWL_CONFIG } from "../currencies/iso4217/zwl";

export type Currency<TAmount> = {
    /**
   * The unique code of the currency.
   */
  readonly code: string;
  /**
   * The base, or radix of the currency.
   */
  readonly base: TAmount | readonly TAmount[];
  /**
   * The exponent of the currency.
   */
  readonly exponent: TAmount;
}



const createCurrency =(config: CurrencyConfig): Currency<number> => {
    return {
        code: config.code,
        base: config.base ?? 10,
        exponent: config.precision,
    }
}

export const AED = createCurrency(AED_CONFIG);
export const AFN = createCurrency(AFN_CONFIG);
export const ALL = createCurrency(ALL_CONFIG);
export const AMD = createCurrency(AMD_CONFIG);
export const ANG = createCurrency(ANG_CONFIG);
export const AOA = createCurrency(AOA_CONFIG);
export const ARS = createCurrency(ARS_CONFIG);
export const AUD = createCurrency(AUD_CONFIG);
export const AWG = createCurrency(AWG_CONFIG);
export const AZN = createCurrency(AZN_CONFIG);
export const BAM = createCurrency(BAM_CONFIG);
export const BBD = createCurrency(BBD_CONFIG);
export const BDT = createCurrency(BDT_CONFIG);
export const BGN = createCurrency(BGN_CONFIG);
export const BHD = createCurrency(BHD_CONFIG);
export const BIF = createCurrency(BIF_CONFIG);
export const BMD = createCurrency(BMD_CONFIG);
export const BND = createCurrency(BND_CONFIG);
export const BOB = createCurrency(BOB_CONFIG);
export const BOV = createCurrency(BOV_CONFIG);
export const BRL = createCurrency(BRL_CONFIG);
export const BSD = createCurrency(BSD_CONFIG);
export const BTN = createCurrency(BTN_CONFIG);
export const BWP = createCurrency(BWP_CONFIG);
export const BYN = createCurrency(BYN_CONFIG);
export const BZD = createCurrency(BZD_CONFIG);
export const CAD = createCurrency(CAD_CONFIG);
export const CDF = createCurrency(CDF_CONFIG);
export const CHE = createCurrency(CHE_CONFIG);
export const CHF = createCurrency(CHF_CONFIG);
export const CHW = createCurrency(CHW_CONFIG);
export const CLF = createCurrency(CLF_CONFIG);
export const CLP = createCurrency(CLP_CONFIG);
export const CNY = createCurrency(CNY_CONFIG);
export const COP = createCurrency(COP_CONFIG);
export const COU = createCurrency(COU_CONFIG);
export const CRC = createCurrency(CRC_CONFIG);
export const CUC = createCurrency(CUC_CONFIG);
export const CUP = createCurrency(CUP_CONFIG);
export const CVE = createCurrency(CVE_CONFIG);
export const CZK = createCurrency(CZK_CONFIG);
export const DJF = createCurrency(DJF_CONFIG);
export const DKK = createCurrency(DKK_CONFIG);
export const DOP = createCurrency(DOP_CONFIG);
export const DZD = createCurrency(DZD_CONFIG);
export const EGP = createCurrency(EGP_CONFIG);
export const ERN = createCurrency(ERN_CONFIG);
export const ETB = createCurrency(ETB_CONFIG);
export const EUR = createCurrency(EUR_CONFIG);
export const FJD = createCurrency(FJD_CONFIG);
export const FKP = createCurrency(FKP_CONFIG);
export const GBP = createCurrency(GBP_CONFIG);
export const GEL = createCurrency(GEL_CONFIG);
export const GHS = createCurrency(GHS_CONFIG);
export const GIP = createCurrency(GIP_CONFIG);
export const GMD = createCurrency(GMD_CONFIG);
export const GNF = createCurrency(GNF_CONFIG);
export const GTQ = createCurrency(GTQ_CONFIG);
export const GYD = createCurrency(GYD_CONFIG);
export const HKD = createCurrency(HKD_CONFIG);
export const HNL = createCurrency(HNL_CONFIG);
export const HRK = createCurrency(HRK_CONFIG);
export const HTG = createCurrency(HTG_CONFIG);
export const HUF = createCurrency(HUF_CONFIG);
export const IDR = createCurrency(IDR_CONFIG);
export const ILS = createCurrency(ILS_CONFIG);
export const INR = createCurrency(INR_CONFIG);
export const IQD = createCurrency(IQD_CONFIG);
export const IRR = createCurrency(IRR_CONFIG);
export const ISK = createCurrency(ISK_CONFIG);
export const JMD = createCurrency(JMD_CONFIG);
export const JOD = createCurrency(JOD_CONFIG);
export const JPY = createCurrency(JPY_CONFIG);
export const KES = createCurrency(KES_CONFIG);
export const KGS = createCurrency(KGS_CONFIG);
export const KHR = createCurrency(KHR_CONFIG);
export const KMF = createCurrency(KMF_CONFIG);
export const KPW = createCurrency(KPW_CONFIG);
export const KRW = createCurrency(KRW_CONFIG);
export const KWD = createCurrency(KWD_CONFIG);
export const KYD = createCurrency(KYD_CONFIG);
export const KZT = createCurrency(KZT_CONFIG);
export const LAK = createCurrency(LAK_CONFIG);
export const LBP = createCurrency(LBP_CONFIG);
export const LKR = createCurrency(LKR_CONFIG);
export const LRD = createCurrency(LRD_CONFIG);
export const LSL = createCurrency(LSL_CONFIG);
export const LYD = createCurrency(LYD_CONFIG);
export const MAD = createCurrency(MAD_CONFIG);
export const MDL = createCurrency(MDL_CONFIG);
export const MGA = createCurrency(MGA_CONFIG);
export const MKD = createCurrency(MKD_CONFIG);
export const MMK = createCurrency(MMK_CONFIG);
export const MNT = createCurrency(MNT_CONFIG);
export const MOP = createCurrency(MOP_CONFIG);
export const MRU = createCurrency(MRU_CONFIG);
export const MUR = createCurrency(MUR_CONFIG);
export const MVR = createCurrency(MVR_CONFIG);
export const MWK = createCurrency(MWK_CONFIG);
export const MXN = createCurrency(MXN_CONFIG);
export const MXV = createCurrency(MXV_CONFIG);
export const MYR = createCurrency(MYR_CONFIG);
export const MZN = createCurrency(MZN_CONFIG);
export const NAD = createCurrency(NAD_CONFIG);
export const NGN = createCurrency(NGN_CONFIG);
export const NIO = createCurrency(NIO_CONFIG);
export const NOK = createCurrency(NOK_CONFIG);
export const NPR = createCurrency(NPR_CONFIG);
export const NZD = createCurrency(NZD_CONFIG);
export const OMR = createCurrency(OMR_CONFIG);
export const PAB = createCurrency(PAB_CONFIG);
export const PEN = createCurrency(PEN_CONFIG);
export const PGK = createCurrency(PGK_CONFIG);
export const PHP = createCurrency(PHP_CONFIG);
export const PKR = createCurrency(PKR_CONFIG);
export const PLN = createCurrency(PLN_CONFIG);
export const PYG = createCurrency(PYG_CONFIG);
export const QAR = createCurrency(QAR_CONFIG);
export const RON = createCurrency(RON_CONFIG);
export const RSD = createCurrency(RSD_CONFIG);
export const RUB = createCurrency(RUB_CONFIG);
export const RWF = createCurrency(RWF_CONFIG);
export const SAR = createCurrency(SAR_CONFIG);
export const SBD = createCurrency(SBD_CONFIG);
export const SCR = createCurrency(SCR_CONFIG);
export const SDG = createCurrency(SDG_CONFIG);
export const SEK = createCurrency(SEK_CONFIG);
export const SGD = createCurrency(SGD_CONFIG);
export const SHP = createCurrency(SHP_CONFIG);
export const SLL = createCurrency(SLL_CONFIG);
export const SOS = createCurrency(SOS_CONFIG);
export const SRD = createCurrency(SRD_CONFIG);
export const SSP = createCurrency(SSP_CONFIG);
export const STN = createCurrency(STN_CONFIG);
export const SVC = createCurrency(SVC_CONFIG);
export const SYP = createCurrency(SYP_CONFIG);
export const SZL = createCurrency(SZL_CONFIG);
export const THB = createCurrency(THB_CONFIG);
export const TJS = createCurrency(TJS_CONFIG);
export const TMT = createCurrency(TMT_CONFIG);
export const TND = createCurrency(TND_CONFIG);
export const TOP = createCurrency(TOP_CONFIG);
export const TRY = createCurrency(TRY_CONFIG);
export const TTD = createCurrency(TTD_CONFIG);
export const TWD = createCurrency(TWD_CONFIG);
export const TZS = createCurrency(TZS_CONFIG);
export const UAH = createCurrency(UAH_CONFIG);
export const UGX = createCurrency(UGX_CONFIG);
export const USD = createCurrency(USD_CONFIG);
export const USN = createCurrency(USN_CONFIG);
export const UYI = createCurrency(UYI_CONFIG);
export const UYU = createCurrency(UYU_CONFIG);
export const UYW = createCurrency(UYW_CONFIG);
export const UZS = createCurrency(UZS_CONFIG);
export const VES = createCurrency(VES_CONFIG);
export const VND = createCurrency(VND_CONFIG);
export const VUV = createCurrency(VUV_CONFIG);
export const WST = createCurrency(WST_CONFIG);
export const XAF = createCurrency(XAF_CONFIG);
export const XCD = createCurrency(XCD_CONFIG);
export const XOF = createCurrency(XOF_CONFIG);
export const XPF = createCurrency(XPF_CONFIG);
export const YER = createCurrency(YER_CONFIG);
export const ZAR = createCurrency(ZAR_CONFIG);
export const ZMW = createCurrency(ZMW_CONFIG);
export const ZWL = createCurrency(ZWL_CONFIG);
